TrainingArguments:

  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 4
  weight_decay: 0.01
  logging_steps: 100
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000
  gradient_accumulation_steps: 2 #16